trigger:
- main   # rama que dispara el pipeline

pool:
  name: selfHost   # 👈 nombre de tu agent pool

steps:
  # 1. Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  # 2. Instalar dependencias y compilar
  - script: |
      npm install
      npm run build
    displayName: 'Compilar aplicación React (Vite)'
    shell: powershell   # 👈 evita que intente usar sh en Windows

  # 3. Subir archivos a S3
  - task: AWSShellScript@1
    inputs:
      awsCredentials: 'AWS connection'   # 👈 nombre exacto de tu Service Connection
      regionName: 'us-east-1'            # 👈 cambia si tu bucket está en otra región
      scriptType: 'inline'
      inlineScript: |
        aws s3 sync dist/ s3://rohi-ips-dev/ --delete
    displayName: 'Deploy a S3'
