version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Instalando dependencias...
      - npm install
  build:
    commands:
      - echo Compilando aplicación React...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
